export const FETCH_PRODUCTS_BY_NAME = 'FETCH_PRODUCTS_BY_NAME'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const SELECT_SIMILAR_PRODUCTS = 'SELECT_SIMILAR_PRODUCTS'
export const CREATE_PRODUCT= 'CREATE_PRODUCT';
export const GET_GRAPES= 'GET_GRAPES';

// Render inicial:
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'